name: Build and Test

# Workflow status badges
# Build Status
# Test Coverage
# Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: List files in the repository
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Ensure Rust toolchain is installed
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Merge Vortex_Core from master to main
        run: |
          git fetch origin master
          git checkout main
          git merge origin/master --allow-unrelated-histories
        continue-on-error: true

      - name: Check root Rust crate compiles
        run: cargo build --release
        working-directory: .

      - name: Build wheel (root crate)
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist
          working-directory: .

      - name: Install wheel and test
        run: |
          pip install nexa-vortex --find-links dist --force-reinstall
          pytest ./python/tests/test_core.py
